add step 3

diff --git a/.github/workflows/code_quality.yml b/.github/workflows/code_quality.yml
--- a/.github/workflows/code_quality.yml
+++ b/.github/workflows/code_quality.yml
@@ -4,7 +4,7 @@ on: [push, pull_request]
 
 jobs:
 
-################################ STEP 1: Code Quality Analysis ################################
+################################ STEP 1: Code Quality ################################
   code-quality-analysis:
       runs-on: ubuntu-latest
       env:
@@ -32,22 +32,21 @@ jobs:
           rust-code-analysis-cli --metrics -O json --pr -o "$HOME/rca-json" -p $PWD
 
       - name: Evaluate code quality
-        run: |
-          .github/scripts/main.sh
+        run: .github/scripts/main.sh
 
       - name: Prepare Step 1 artifacts
         run: |
           mkdir -p $HOME/final-artifacts/step1
-          cp -r $HOME/rca-json/* $HOME/final-artifacts/step1 || echo "No RCA JSON files to copy"
-          cp -r $HOME/code-quality-report/* $HOME/final-artifacts/step1 || echo "No code quality report files to copy"
+          cp -r $HOME/rca-json/* $HOME/final-artifacts/step1/ || echo "No RCA JSON files to copy"
+          cp -r $HOME/code-quality-report/* $HOME/final-artifacts/step1/ || echo "No code quality report files to copy"
 
-      - name: Upload Step 1 artifacts
+      - name: Save code-quality artifacts temporarily
         uses: actions/upload-artifact@v4
         with:
-          name: analysis-results
+          name: partial-artifacts
           path: ~/final-artifacts/
 
-################################ STEP 2: Code Quality Report ################################
+################################ STEP 2: Anomaly Detection ################################
   anomaly-detection:
     runs-on: ubuntu-latest
     needs: code-quality-analysis
@@ -55,23 +54,69 @@ jobs:
     steps:
     - uses: actions/checkout@v4
 
-    - name: Download previous artifacts
+    - name: Download partial artifacts
       uses: actions/download-artifact@v4
       with:
-        name: analysis-results
+        name: partial-artifacts
         path: ~/final-artifacts/
 
     - name: Simulated anomaly detection step
       run: |
-        echo "Starting anomaly detection analysis..."
-        echo "Analysing patterns and detecting potential anomalies..."
-        echo "Anomaly detection completed successfully."
-
         mkdir -p $HOME/final-artifacts/step2
         echo "Anomaly Detection Report" > $HOME/final-artifacts/step2/anomaly-detection-report.txt
 
-    - name: Upload updated artifacts
+    - name: Save step1+step2 artifacts
       uses: actions/upload-artifact@v4
       with:
-        name: analysis-results
+        name: partial-artifacts
         path: ~/final-artifacts/
+        overwrite: true
+
+################################ STEP 3: Manifest-Producer Analysis ################################
+  manifest-producer:
+    runs-on: ubuntu-latest
+    needs: anomaly-detection
+
+    steps:
+      - uses: actions/checkout@v4
+
+      - name: Download partial artifacts
+        uses: actions/download-artifact@v4
+        with:
+          name: partial-artifacts
+          path: ~/final-artifacts/
+
+      - name: Install musl
+        run: | 
+          sudo apt update
+          sudo apt install -y musl-dev musl-tools
+
+      - name: Install Rust toolchain
+        uses: dtolnay/rust-toolchain@stable
+        with:
+          target: x86_64-unknown-linux-musl
+
+      - name: Build firmware statically with musl
+        run: |
+          mkdir -p $HOME/final-artifacts/step3
+          cargo build --release --target=x86_64-unknown-linux-musl
+          cp target/x86_64-unknown-linux-musl/release/light-firmware $HOME/elf_binary
+
+      - name: Clone manifest-producer repository
+        run: |
+          cd $HOME
+          git clone https://github.com/SoftengPoliTo/manifest-producer.git
+          cd manifest-producer
+
+      - name: Run manifest producer
+        run: |
+          cd $HOME/manifest-producer
+          cargo run $HOME/work/light-firmware/light-firmware/target/x86_64-unknown-linux-musl/release/light-firmware || echo "Failed to run manifest-producer, skipping step3 analysis"
+          cp -r ./examples/results/light-firmware/* ../final-artifacts/step3/ 2>/dev/null || echo "No light-firmware found, skipping copy"
+          cp ./examples/results/light-firmware_checker.json ../final-artifacts/step3/ 2>/dev/null || echo "No light-firmware.json found, skipping copy"
+
+      - name: Upload final artifacts
+        uses: actions/upload-artifact@v4
+        with:
+          name: analysis-results
+          path: ~/final-artifacts/
